// Per-user completion checklists (mask shards, tools, charms, bosses, etc.) — purely for the
// player's own tracking. Unlike the progress sidebar (`beats`, loaded from the backend and used to
// build the spoiler gate), this list never reaches retrieval/filtering. It's static, game-authored
// data, checked state lives client-side (+ Supabase sync), and the only thing the backend does with
// it is fold a plain-text summary into the prompt so the guide is *aware* of what's been collected —
// see `collectedSummary()` below and `collected_summary` on the query payload.
//
// Sourced from community 100%/112% checklists (game-checklists.com) and grouped to match their
// categories.

export const CHECKLISTS = {
  hollow_knight: [
    {
      key: "mask_shards",
      label: "Mask Shards",
      items: [
        { id: "hk-mask-1", name: "Mask Shard 1", location: "Dirtmouth", note: "Sold by Sly for 150 Geo" },
        { id: "hk-mask-2", name: "Mask Shard 2", location: "Dirtmouth", note: "Sold by Sly for 500 Geo after buying Mask Shard 1" },
        { id: "hk-mask-3", name: "Mask Shard 3", location: "Dirtmouth", note: "Sold by Sly for 800 Geo after bringing him the Shopkeeper's Key" },
        { id: "hk-mask-4", name: "Mask Shard 4", location: "Dirtmouth", note: "Sold by Sly for 1500 Geo after bringing him the Shopkeeper's Key" },
        { id: "hk-mask-5", name: "Mask Shard 5", location: "Dirtmouth", note: "Found in Bretta's house after rescuing her in Fungal Wastes" },
        { id: "hk-mask-6", name: "Mask Shard 6", location: "Forgotten Crossroads", note: "In a room directly below the Hot Springs Bench" },
        { id: "hk-mask-7", name: "Mask Shard 7", location: "Forgotten Crossroads", note: "Defeat Brooding Mawlek" },
        { id: "hk-mask-8", name: "Mask Shard 8", location: "Forgotten Crossroads", note: "Reward from Grubfather for saving 5 Grubs" },
        { id: "hk-mask-9", name: "Mask Shard 9", location: "Greenpath", note: "Defeat No Eyes, in the right edge of Stone Sanctuary" },
        { id: "hk-mask-10", name: "Mask Shard 10", location: "Fungal Wastes", note: "Queen's Station — requires Mantis Claw" },
        { id: "hk-mask-11", name: "Mask Shard 11", location: "Royal Waterways", note: "Left edge, close to Cornifer's location" },
        { id: "hk-mask-12", name: "Mask Shard 12", location: "Crystal Peak", note: "Defeat Enraged Guardian, the Dream version of Crystal Guardian" },
        { id: "hk-mask-13", name: "Mask Shard 13", location: "Resting Grounds", note: "Reward from Seer for 1500 Essence" },
        { id: "hk-mask-14", name: "Mask Shard 14", location: "Resting Grounds", note: "Reward from Grey Mourner for delivering the Delicate Flower" },
        { id: "hk-mask-15", name: "Mask Shard 15", location: "Deepnest", note: "Right above the main entrance from Mantis Lords" },
        { id: "hk-mask-16", name: "Mask Shard 16", location: "The Hive", note: "Bait the Hive Guardian into the honey wall to break it" },
      ],
    },
    {
      key: "vessel_fragments",
      label: "Vessel Fragments",
      items: [
        { id: "hk-vessel-1", name: "Vessel Fragment 1", location: "Dirtmouth", note: "Sold by Sly for 550 Geo" },
        { id: "hk-vessel-2", name: "Vessel Fragment 2", location: "Dirtmouth", note: "Sold by Sly for 900 Geo after bringing him the Shopkeeper's Key" },
        { id: "hk-vessel-3", name: "Vessel Fragment 3", location: "Forgotten Crossroads", note: "Left of the elevator from City of Tears" },
        { id: "hk-vessel-4", name: "Vessel Fragment 4", location: "Greenpath", note: "On the path towards Queen's Gardens" },
        { id: "hk-vessel-5", name: "Vessel Fragment 5", location: "City of Tears", note: "In a tower right above King's Station" },
        { id: "hk-vessel-6", name: "Vessel Fragment 6", location: "Ancient Basin", note: "Drop 3000 Geo at the Pale King statue fountain" },
        { id: "hk-vessel-7", name: "Vessel Fragment 7", location: "Resting Grounds", note: "Reward from Seer for 700 Essence" },
        { id: "hk-vessel-8", name: "Vessel Fragment 8", location: "Howling Cliffs", note: "Stag Nest — needs all other Stag Stations unlocked" },
        { id: "hk-vessel-9", name: "Vessel Fragment 9", location: "Deepnest", note: "Right of the Hot Springs Bench, Garpede parkour room" },
      ],
    },
    {
      key: "charms",
      label: "Charms",
      items: [
        { id: "hk-charm-1", name: "Wayward Compass", location: "Dirtmouth", note: "Sold by Iselda for 220 Geo" },
        { id: "hk-charm-2", name: "Gathering Swarm", location: "Dirtmouth", note: "Sold by Sly for 300 Geo" },
        { id: "hk-charm-3", name: "Stalwart Shell", location: "Dirtmouth", note: "Sold by Sly for 200 Geo" },
        { id: "hk-charm-4", name: "Soul Catcher", location: "Forgotten Crossroads", note: "Found within the Ancestral Mound" },
        { id: "hk-charm-5", name: "Shaman Stone", location: "Forgotten Crossroads", note: "Sold by Salubra for 220 Geo" },
        { id: "hk-charm-6", name: "Soul Eater", location: "Resting Grounds", note: "Behind a breakable floor in the tunnel sections" },
        { id: "hk-charm-7", name: "Dashmaster", location: "Fungal Wastes", note: "Found near the Bretta Bench" },
        { id: "hk-charm-8", name: "Sprintmaster", location: "Dirtmouth", note: "Sold by Sly for 400 Geo after bringing him the Shopkeeper's Key" },
        { id: "hk-charm-9", name: "Grubsong", location: "Forgotten Crossroads", note: "Reward from Grubfather for saving 10 Grubs" },
        { id: "hk-charm-10", name: "Grubberfly's Elegy", location: "Forgotten Crossroads", note: "Reward from Grubfather for saving all 46 Grubs" },
        { id: "hk-charm-11", name: "Fragile / Unbreakable Heart", location: "Fungal Wastes", note: "Sold by Leg Eater for 350 Geo; can be upgraded" },
        { id: "hk-charm-12", name: "Fragile / Unbreakable Greed", location: "Fungal Wastes", note: "Sold by Leg Eater for 250 Geo; can be upgraded" },
        { id: "hk-charm-13", name: "Fragile / Unbreakable Strength", location: "Fungal Wastes", note: "Sold by Leg Eater for 600 Geo; can be upgraded" },
        { id: "hk-charm-14", name: "Spell Twister", location: "City of Tears", note: "Atop the Soul Sanctum, in a room full of Mistakes" },
        { id: "hk-charm-15", name: "Steady Body", location: "Forgotten Crossroads", note: "Sold by Salubra for 120 Geo" },
        { id: "hk-charm-16", name: "Heavy Blow", location: "Dirtmouth", note: "Sold by Sly for 350 Geo after bringing him the Shopkeeper's Key" },
        { id: "hk-charm-17", name: "Quick Slash", location: "Kingdom's Edge", note: "Below Nailmaster Oro's hut" },
        { id: "hk-charm-18", name: "Longnail", location: "Forgotten Crossroads", note: "Sold by Salubra for 300 Geo" },
        { id: "hk-charm-19", name: "Mark of Pride", location: "Fungal Wastes", note: "Reward room for defeating the Mantis Lords" },
        { id: "hk-charm-20", name: "Fury of the Fallen", location: "Howling Cliffs", note: "King's Pass tutorial section, after pogo-ing spikes" },
        { id: "hk-charm-21", name: "Thorns of Agony", location: "Greenpath", note: "Parkour section with electricity and thorns" },
        { id: "hk-charm-22", name: "Baldur Shell", location: "Howling Cliffs", note: "First room — jump into the suspicious chest" },
        { id: "hk-charm-23", name: "Flukenest", location: "Royal Waterways", note: "Reward for defeating Flukemarm" },
        { id: "hk-charm-24", name: "Defender's Crest", location: "Royal Waterways", note: "Reward for defeating Dung Defender" },
        { id: "hk-charm-25", name: "Glowing Womb", location: "Forgotten Crossroads", note: "Aspid section revealed by a breaking wall" },
        { id: "hk-charm-26", name: "Quick Focus", location: "Forgotten Crossroads", note: "Sold by Salubra for 800 Geo" },
        { id: "hk-charm-27", name: "Deep Focus", location: "Crystal Peak", note: "Behind a breakable wall near a pickaxe-wielding enemy" },
        { id: "hk-charm-28", name: "Lifeblood Heart", location: "Forgotten Crossroads", note: "Sold by Salubra for 250 Geo" },
        { id: "hk-charm-29", name: "Lifeblood Core", location: "Ancient Basin", note: "In The Abyss — needs 15+ Lifeblood hearts to open the door" },
        { id: "hk-charm-30", name: "Joni's Blessing", location: "Howling Cliffs", note: "Found in Joni's Repose" },
        { id: "hk-charm-31", name: "Hiveblood", location: "The Hive", note: "Reward for defeating Hive Knight" },
        { id: "hk-charm-32", name: "Spore Shroom", location: "Fungal Wastes", note: "Room directly below Queen's Station" },
        { id: "hk-charm-33", name: "Sharp Shadow", location: "Deepnest", note: "Near the Hot Springs Bench — Shade Cloak required" },
        { id: "hk-charm-34", name: "Shape of Unn", location: "Greenpath", note: "Behind the Lake of Unn — Crystal Dash required" },
        { id: "hk-charm-35", name: "Nailmaster's Glory", location: "Dirtmouth", note: "Reward from Sly after learning all 3 Nail Arts" },
        { id: "hk-charm-36", name: "Weaversong", location: "Deepnest", note: "In the Weavernest, mid-Deepnest" },
        { id: "hk-charm-37", name: "Dream Wielder", location: "Resting Grounds", note: "Reward from Seer for 500 Essence" },
        { id: "hk-charm-38", name: "Dreamshield", location: "Resting Grounds", note: "Behind a breakable wall in the tall room" },
        { id: "hk-charm-39", name: "Grimmchild / Carefree Melody", location: "Dirtmouth", note: "Grimmchild from Troupe Master Grimm; Carefree Melody after banishing the Troupe" },
        { id: "hk-charm-40", name: "Kingsoul / Void Heart", location: "Ancient Basin", note: "Kingsoul from White Fragments; Void Heart at the Abyss's Birthplace" },
      ],
    },
    {
      key: "spells",
      label: "Spells",
      items: [
        { id: "hk-spell-1", name: "Vengeful Spirit", location: "Forgotten Crossroads", note: "Defeat False Knight, into the Ancestral Mound" },
        { id: "hk-spell-2", name: "Shade Soul", location: "City of Tears", note: "Soul Sanctum, near its Bench shortcut — Elegant Key required" },
        { id: "hk-spell-3", name: "Desolate Dive", location: "City of Tears", note: "Defeat Soul Master" },
        { id: "hk-spell-4", name: "Descending Dark", location: "Crystal Peak", note: "Crystallised Mound, past the hole to Resting Grounds" },
        { id: "hk-spell-5", name: "Howling Wraiths", location: "Fog Canyon", note: "Found in the Overgrown Mound" },
        { id: "hk-spell-6", name: "Abyss Shriek", location: "Ancient Basin", note: "In The Abyss — use Howling Wraiths before the large face" },
      ],
    },
    {
      key: "abilities",
      label: "Abilities",
      items: [
        { id: "hk-ability-1", name: "Mothwing Cloak (Dash)", location: "Greenpath", note: "Defeat Hornet" },
        { id: "hk-ability-2", name: "Mantis Claw (Wall Jump)", location: "Fungal Wastes", note: "Top of Mantis Village, after switching a few levers" },
        { id: "hk-ability-3", name: "Crystal Heart (Super Dash)", location: "Crystal Peak", note: "Rightmost edge of Crystal Peak" },
        { id: "hk-ability-4", name: "Isma's Tear (Acid Immunity)", location: "Royal Waterways", note: "Right part, accessible with Crystal Heart" },
        { id: "hk-ability-5", name: "Monarch Wings (Double Jump)", location: "Ancient Basin", note: "Defeat Broken Vessel" },
        { id: "hk-ability-6", name: "King's Brand (Abyss access)", location: "Kingdom's Edge", note: "Defeat Hornet Sentinel, into the Cast-Off Shell" },
        { id: "hk-ability-7", name: "Shade Cloak (Ghost Dash)", location: "Ancient Basin", note: "In The Abyss, far right — after activating the lighthouse" },
      ],
    },
    {
      key: "dream_nail",
      label: "Dream Nail",
      items: [
        { id: "hk-dreamnail-1", name: "Get the Dream Nail", location: "Resting Grounds", note: "Encounter the Three Watcher Statues" },
        { id: "hk-dreamnail-2", name: "Get Awakened Dream Nail", location: "Resting Grounds", note: "Gather 1800 Essence" },
        { id: "hk-dreamnail-3", name: "Hear the Seer's Final Words", location: "Resting Grounds", note: "Gather 2400 Essence" },
      ],
    },
    {
      key: "nail_upgrades",
      label: "Nail Upgrades",
      items: [
        { id: "hk-nailup-1", name: "Sharpened Nail", location: "City of Tears", note: "Costs 250 Geo" },
        { id: "hk-nailup-2", name: "Channeled Nail", location: "City of Tears", note: "Costs 800 Geo and 1 Pale Ore" },
        { id: "hk-nailup-3", name: "Coiled Nail", location: "City of Tears", note: "Costs 2000 Geo and 2 Pale Ores" },
        { id: "hk-nailup-4", name: "Pure Nail", location: "City of Tears", note: "Costs 4000 Geo and 3 Pale Ores" },
      ],
    },
    {
      key: "nail_arts",
      label: "Nail Arts",
      items: [
        { id: "hk-nailart-1", name: "Great Slash", location: "Greenpath", note: "Learn from Nailmaster Sheo" },
        { id: "hk-nailart-2", name: "Cyclone Slash", location: "Howling Cliffs", note: "Learn from Nailmaster Mato" },
        { id: "hk-nailart-3", name: "Dash Slash", location: "Kingdom's Edge", note: "Learn from Nailmaster Oro for 800 Geo" },
      ],
    },
    {
      key: "colosseum",
      label: "Colosseum of Fools",
      items: [
        { id: "hk-colosseum-1", name: "Trial of the Warrior", location: "Kingdom's Edge", note: "Easiest trial — 1000 Geo, 1 Charm Notch" },
        { id: "hk-colosseum-2", name: "Trial of the Conqueror", location: "Kingdom's Edge", note: "Medium trial — 2000 Geo, 1 Pale Ore" },
        { id: "hk-colosseum-3", name: "Trial of the Fool", location: "Kingdom's Edge", note: "Hardest trial — 3000 Geo" },
      ],
    },
    {
      key: "godhome",
      label: "Godhome Pantheons",
      items: [
        { id: "hk-godhome-1", name: "Reach Godhome", location: "Royal Waterways", note: "Pick up the Godtuner in the Junk Pit" },
        { id: "hk-godhome-2", name: "Pantheon of the Master", location: "Godhome", note: "First Pantheon" },
        { id: "hk-godhome-3", name: "Pantheon of the Artist", location: "Godhome", note: "Second Pantheon" },
        { id: "hk-godhome-4", name: "Pantheon of the Sage", location: "Godhome", note: "Third Pantheon" },
        { id: "hk-godhome-5", name: "Pantheon of the Knight", location: "Godhome", note: "Fourth Pantheon" },
      ],
    },
    {
      key: "bosses",
      label: "Bosses",
      items: [
        { id: "hk-boss-1", name: "Gruz Mother", location: "Forgotten Crossroads", note: "Right and below the Stag station" },
        { id: "hk-boss-2", name: "False Knight", location: "Forgotten Crossroads", note: "Above the Stag station" },
        { id: "hk-boss-3", name: "Brooding Mawlek", location: "Forgotten Crossroads", note: "Accessible from the main tall room" },
        { id: "hk-boss-4", name: "Hornet", location: "Greenpath", note: "Above the Stag station" },
        { id: "hk-boss-5", name: "Mantis Lords", location: "Fungal Wastes", note: "Bottom of Mantis Village" },
        { id: "hk-boss-6", name: "Soul Master", location: "City of Tears", note: "Top of Soul Sanctum" },
        { id: "hk-boss-7", name: "The Collector", location: "City of Tears", note: "Tower of Love" },
        { id: "hk-boss-8", name: "Watcher Knights", location: "City of Tears", note: "Watcher's Spire, guarding Lurien" },
        { id: "hk-boss-9", name: "Dung Defender", location: "Royal Waterways", note: "Grants access to the eastern part" },
        { id: "hk-boss-10", name: "Broken Vessel", location: "Ancient Basin", note: "End of Ancient Basin" },
        { id: "hk-boss-11", name: "Nosk", location: "Deepnest", note: "Bottom of Deepnest, behind breakable walls" },
        { id: "hk-boss-12", name: "Hornet Sentinel", location: "Kingdom's Edge", note: "Right edge of Kingdom's Edge" },
        { id: "hk-boss-13", name: "Hive Knight", location: "The Hive", note: "End of The Hive" },
        { id: "hk-boss-14", name: "Uumuu", location: "Fog Canyon", note: "Teacher's Archives, guarding Monomon" },
        { id: "hk-boss-15", name: "Traitor Lord", location: "Queen's Gardens", note: "End of Queen's Gardens" },
        { id: "hk-boss-16", name: "Troupe Master Grimm", location: "Dirtmouth", note: "First Grimm fight, after the Troupe arrives" },
      ],
    },
    {
      key: "dream_bosses",
      label: "Warrior Dreams",
      items: [
        { id: "hk-dreamboss-1", name: "Galien", location: "Deepnest", note: "Below where you get the Tramway Pass" },
        { id: "hk-dreamboss-2", name: "Marmu", location: "Queen's Gardens", note: "Left of the Queen's Gardens Stag Station Bench" },
        { id: "hk-dreamboss-3", name: "Markoth", location: "Kingdom's Edge", note: "Below the Surface Bench — Shade Cloak required" },
        { id: "hk-dreamboss-4", name: "Xero", location: "Resting Grounds", note: "Main floor of Resting Grounds" },
        { id: "hk-dreamboss-5", name: "No Eyes", location: "Greenpath", note: "Stone Sanctuary" },
        { id: "hk-dreamboss-6", name: "Elder Hu", location: "Fungal Wastes", note: "Room above the entrance to City of Tears" },
        { id: "hk-dreamboss-7", name: "Gorb", location: "Howling Cliffs", note: "Very top of Howling Cliffs" },
        { id: "hk-dreamboss-8", name: "Nightmare King Grimm", location: "Dirtmouth", note: "Second Grimm fight, after gathering the required Grimmkin" },
      ],
    },
    {
      key: "dreamers",
      label: "Dreamers",
      items: [
        { id: "hk-dreamer-1", name: "Lurien the Watcher", location: "City of Tears", note: "Watcher's Spire, protected by Watcher Knights" },
        { id: "hk-dreamer-2", name: "Herrah the Beast", location: "Deepnest", note: "Beast's Den" },
        { id: "hk-dreamer-3", name: "Monomon the Teacher", location: "Fog Canyon", note: "Teacher's Archives, protected by Uumuu" },
      ],
    },
  ],

  silksong: [
    {
      key: "mask_shards",
      label: "Mask Shards",
      items: [
        { id: "ss-mask-1", name: "Mask Shard 1", location: "Bone Bottom", note: "Sold in Bone Bottom for 300 Rosaries" },
        { id: "ss-mask-2", name: "Mask Shard 2", location: "Wormways", note: "Behind a breakable wall to the south" },
        { id: "ss-mask-3", name: "Mask Shard 3", location: "Weavenest Atla", note: "Elevator shaft, east exit — Needolin required" },
        { id: "ss-mask-4", name: "Mask Shard 4", location: "Deep Docks", note: "Above the westernmost bench — Cling Grip required" },
        { id: "ss-mask-5", name: "Mask Shard 5", location: "Far Fields", note: "Above Seamstress's Home — Drifter's Cloak required" },
        { id: "ss-mask-6", name: "Mask Shard 6", location: "Far Fields", note: "Skull Cavern (no ground arena) — Clawline required" },
        { id: "ss-mask-7", name: "Mask Shard 7", location: "Bellhart", note: "Savage Beastfly quest" },
        { id: "ss-mask-8", name: "Mask Shard 8", location: "Shellwood", note: "Flower trap behind a breakable wall" },
        { id: "ss-mask-9", name: "Mask Shard 9", location: "Blasted Steps", note: "Secret jump near the west border" },
        { id: "ss-mask-10", name: "Mask Shard 10", location: "Wisp Thicket", note: "Parkour challenge near the east edge — Faydown Cloak required" },
        { id: "ss-mask-11", name: "Mask Shard 11", location: "Cogwork Core", note: "Arena southeast of the central Bench" },
        { id: "ss-mask-12", name: "Mask Shard 12", location: "Choral Chambers", note: "Sold in Songclave for 750 Rosaries" },
        { id: "ss-mask-13", name: "Mask Shard 13", location: "Whispering Vaults", note: "Box puzzle in the eastern part — Cling Grip required" },
        { id: "ss-mask-14", name: "Mask Shard 14", location: "Bilewater", note: "Toxic path with a jumping wormfish — Clawline required" },
        { id: "ss-mask-15", name: "Mask Shard 15", location: "The Slab", note: "Parkour challenge, north-east — Apostate Key, Clawline required" },
        { id: "ss-mask-16", name: "Mask Shard 16", location: "Mount Fay", note: "Floating near the west bench — Faydown Cloak required" },
        { id: "ss-mask-17", name: "Mask Shard 17", location: "Far Fields (Act 3)", note: "Sprintmaster Swift quest" },
        { id: "ss-mask-18", name: "Mask Shard 18", location: "Bellhart (Act 3)", note: "Void Hearts quest" },
        { id: "ss-mask-19", name: "Mask Shard 19", location: "Bellhart (Act 3)", note: "Gurr the Outcast quest" },
        { id: "ss-mask-20", name: "Mask Shard 20", location: "Mount Fay (Act 3)", note: "Brightvein — Silk Soar required" },
      ],
    },
    {
      key: "spool_fragments",
      label: "Spool Fragments",
      items: [
        { id: "ss-spool-1", name: "Spool Fragment 1", location: "Bone Bottom", note: "Trap room east of the lift" },
        { id: "ss-spool-2", name: "Spool Fragment 2", location: "Weavenest Atla", note: "Elevator shaft, west exit — Cling Grip required" },
        { id: "ss-spool-3", name: "Spool Fragment 3", location: "Deep Docks", note: "Parkour challenge near Forge Daughter" },
        { id: "ss-spool-4", name: "Spool Fragment 4", location: "Deep Docks", note: "Parkour challenge in the southeast — Clawline required" },
        { id: "ss-spool-5", name: "Spool Fragment 5", location: "Greymoor", note: "Near the Sinner's Road shortcut — Cling Grip required" },
        { id: "ss-spool-6", name: "Spool Fragment 6", location: "Bellhart", note: "First Courier quest" },
        { id: "ss-spool-7", name: "Spool Fragment 7", location: "Blasted Steps", note: "Sold by Grindle for 680 Rosaries" },
        { id: "ss-spool-8", name: "Spool Fragment 8", location: "Grand Gate", note: "Moving platforms challenge — Cling Grip required" },
        { id: "ss-spool-9", name: "Spool Fragment 9", location: "Underworks", note: "West of the Cauldron — Cling Grip required" },
        { id: "ss-spool-10", name: "Spool Fragment 10", location: "Underworks", note: "In a pit near the lift to Trobbio's arena — 300 Rosaries" },
        { id: "ss-spool-11", name: "Spool Fragment 11", location: "Whiteward", note: "Below the main lift — White Key required" },
        { id: "ss-spool-12", name: "Spool Fragment 12", location: "Cogwork Core", note: "Behind a Cogwork bug blocking a lever, southeast" },
        { id: "ss-spool-13", name: "Spool Fragment 13", location: "Choral Chambers", note: "Sold in Songclave for 500 Rosaries, after the first Jubilana quest" },
        { id: "ss-spool-14", name: "Spool Fragment 14", location: "Choral Chambers", note: "Songclave — Sherma quest" },
        { id: "ss-spool-15", name: "Spool Fragment 15", location: "Memorium", note: "Parkour challenge in the west room — Faydown Cloak required" },
        { id: "ss-spool-16", name: "Spool Fragment 16", location: "High Halls", note: "Parkour challenge in the first tower — Faydown Cloak required" },
        { id: "ss-spool-17", name: "Spool Fragment 17", location: "The Slab", note: "Mount Fay viewpoint — Apostate Key, Cling Grip required" },
        { id: "ss-spool-18", name: "Spool Fragment 18", location: "Grand Gate", note: "Find 14 Lost Fleas, given by Mooshka" },
      ],
    },
    {
      key: "tools",
      label: "Tools",
      items: [
        { id: "ss-tool-1", name: "Magnetite Brooch", location: "Bone Bottom", note: "Sold for 120 Rosaries" },
        { id: "ss-tool-2", name: "Druid's Eye", location: "Mosshome", note: "Druid's Mossberry picking quest" },
        { id: "ss-tool-3", name: "Snare Setter", location: "Weavenest Atla", note: "West of the lift shaft — Faydown Cloak required" },
        { id: "ss-tool-4", name: "Weavelight", location: "Weavenest Atla", note: "Duo Moss Mothers, west of the bench" },
        { id: "ss-tool-5", name: "Shard Pendant", location: "The Marrow", note: "Small room west of the central tall area" },
        { id: "ss-tool-6", name: "Straight Pin", location: "The Marrow", note: "Grindle's prison cell" },
        { id: "ss-tool-7", name: "Curveclaw", location: "Hunter's March", note: "Sold by Mottled Skarr for 140 Rosaries" },
        { id: "ss-tool-8", name: "Fractured Mask", location: "Hunter's March", note: "Sold by Mottled Skarr for 260 Rosaries" },
        { id: "ss-tool-9", name: "Magma Bell", location: "Deep Docks", note: "Sold by Forge Daughter — 110 Rosaries, 1 Craftmetal" },
        { id: "ss-tool-10", name: "Sting Shard", location: "Deep Docks", note: "Sold by Forge Daughter — 140 Rosaries, 1 Craftmetal" },
        { id: "ss-tool-11", name: "Flintslate", location: "Deep Docks", note: "Southeast Deep Docks" },
        { id: "ss-tool-12", name: "Warding Bell", location: "Far Fields", note: "Bottom of the central room" },
        { id: "ss-tool-13", name: "Silkspeed Anklets", location: "Far Fields", note: "Weavenest Cindril — Needolin required" },
        { id: "ss-tool-14", name: "Weighted Belt", location: "Far Fields", note: "Sold in Pilgrim's Rest for 160 Rosaries" },
        { id: "ss-tool-15", name: "Threefold Pin", location: "Greymoor", note: "Secret room above Craw House" },
        { id: "ss-tool-16", name: "Flea Brew", location: "Greymoor", note: "Find 5 Fleas and move the caravan" },
        { id: "ss-tool-17", name: "Pimpillo", location: "Greymoor", note: "Yarnaby tower — 1 Craftmetal, Cling Grip required" },
        { id: "ss-tool-18", name: "Compass", location: "Bellhart", note: "Sold by Shakra for 70 Rosaries" },
        { id: "ss-tool-19", name: "Multibinder", location: "Bellhart", note: "Sold for 880 Rosaries, first Courier quest" },
        { id: "ss-tool-20", name: "Longpin", location: "Bellhart", note: "Behind the Shellwood wasp nest" },
        { id: "ss-tool-21", name: "Pollip Pouch", location: "Shellwood", note: "Greyroot Pollip Hearts quest" },
        { id: "ss-tool-22", name: "Dead Bug's Purse", location: "Wormways", note: "Near the northern entrance" },
        { id: "ss-tool-23", name: "Plasmium Phial", location: "Wormways", note: "Alchemist Zylotol quest" },
        { id: "ss-tool-24", name: "Magnetite Dice", location: "Blasted Steps", note: "Win at the dice minigame" },
        { id: "ss-tool-25", name: "Snitch Pick", location: "Blasted Steps", note: "Sold by Grindle for 740 Rosaries" },
        { id: "ss-tool-26", name: "Thief's Mark", location: "Blasted Steps", note: "Sold by Grindle for 350 Rosaries" },
        { id: "ss-tool-27", name: "Conchcutter", location: "Sands of Karak", note: "In Coral Tower" },
        { id: "ss-tool-28", name: "Volt Filament", location: "Sands of Karak", note: "Defeat Voltwyrm" },
        { id: "ss-tool-29", name: "Barbed Bracelet", location: "Sinner's Road", note: "In a pit at the end of the first road" },
        { id: "ss-tool-30", name: "Tacks", location: "Sinner's Road", note: "Muckroaches quest" },
        { id: "ss-tool-31", name: "Wispfire Lantern", location: "Wisp Thicket", note: "Defeat Father of the Flame" },
        { id: "ss-tool-32", name: "Delver's Drill", location: "Underworks", note: "South of the Grand Gate lift" },
        { id: "ss-tool-33", name: "Sawtooth Circlet", location: "Underworks", note: "Sold by Twelfth Architect — 1 Craftmetal, 230 Rosaries" },
        { id: "ss-tool-34", name: "Cogwork Wheel", location: "Underworks", note: "Sold by Twelfth Architect — 1 Craftmetal, 360 Rosaries" },
        { id: "ss-tool-35", name: "Scuttlebrace", location: "Underworks", note: "Sold by Twelfth Architect — 1 Craftmetal, 140 Rosaries" },
        { id: "ss-tool-36", name: "Injector Band", location: "Whiteward", note: "Hidden before the drop to Underworks" },
        { id: "ss-tool-37", name: "Ascendant's Grip", location: "Choral Chambers", note: "Sold in Songclave for 350 Rosaries" },
        { id: "ss-tool-38", name: "Spool Extender", location: "Choral Chambers", note: "Sold in Songclave for 720 Rosaries" },
        { id: "ss-tool-39", name: "Spider Strings", location: "Choral Chambers", note: "Sold in Songclave for 320 Rosaries" },
        { id: "ss-tool-40", name: "Claw Mirror", location: "Whispering Vaults", note: "Defeat Trobbio" },
        { id: "ss-tool-41", name: "Voltvessels", location: "Memorium", note: "Near electric enemies, by the Large Flea" },
        { id: "ss-tool-42", name: "Cogfly", location: "High Halls", note: "Room beside the Drifter's Cloak section — 1 Craftmetal" },
        { id: "ss-tool-43", name: "Rosary Cannon", location: "High Halls", note: "Locked room before the Arena — Simple Key required" },
        { id: "ss-tool-44", name: "Reserve Bind", location: "Choral Chambers", note: "Defeat Second Sentinel" },
        { id: "ss-tool-45", name: "Memory Crystal", location: "Mount Fay", note: "Ice room near the western bench" },
        { id: "ss-tool-46", name: "Pin Badge", location: "Mount Fay (Act 3)", note: "Defeat Pinstress" },
        { id: "ss-tool-47", name: "Wreath of Purity", location: "Putrified Ducts", note: "East of the Bellway" },
        { id: "ss-tool-48", name: "Longclaw", location: "Putrified Ducts", note: "Organ collection quest" },
        { id: "ss-tool-49", name: "Egg of Flealia", location: "Fleatopia", note: "Find every Lost Flea" },
        { id: "ss-tool-50", name: "Quick Sling", location: "Bilewater", note: "Secret area behind breakable ceilings" },
        { id: "ss-tool-51", name: "Throwing Rings", location: "Bilewater", note: "Shakra quest" },
        { id: "ss-tool-52", name: "Silkshot", location: "Bilewater", note: "Ruined Tool in east Bilewater" },
      ],
    },
    {
      key: "silk_skills",
      label: "Silk Skills",
      items: [
        { id: "ss-silkskill-1", name: "Silkspear", location: "Mosshome", note: "Complete Mosshome" },
        { id: "ss-silkskill-2", name: "Thread Storm", location: "Greymoor", note: "Defeat the Craw gauntlet and pogo outside" },
        { id: "ss-silkskill-3", name: "Cross Stitch", location: "Exhaust Organ", note: "Defeat Phantom" },
        { id: "ss-silkskill-4", name: "Sharpdart", location: "Wormways", note: "Weavenest Karn — Needolin, Clawline required" },
        { id: "ss-silkskill-5", name: "Rune Rage", location: "The Slab", note: "Defeat First Sinner" },
        { id: "ss-silkskill-6", name: "Pale Nails", location: "The Cradle (Act 3)", note: "En route to the surface village — Silk Soar required" },
      ],
    },
    {
      key: "abilities",
      label: "Abilities",
      items: [
        { id: "ss-ability-1", name: "Swift Step", location: "Deep Docks", note: "Complete Deep Docks" },
        { id: "ss-ability-2", name: "Cling Grip", location: "Shellwood", note: "Defeat Sister Splinter" },
        { id: "ss-ability-3", name: "Needolin", location: "Bellhart", note: "Defeat Widow — Cling Grip required" },
        { id: "ss-ability-4", name: "Needle Strike", location: "Blasted Steps", note: "Given by Pinstress" },
        { id: "ss-ability-5", name: "Clawline", location: "Underworks", note: "Complete The Cauldron" },
        { id: "ss-ability-6", name: "Silk Soar", location: "The Abyss", note: "Complete The Abyss for the first time" },
      ],
    },
    {
      key: "crests",
      label: "Crests",
      items: [
        { id: "ss-crest-1", name: "Crest of Wanderer", location: "Bone Bottom", note: "Chapel of the Wanderer in Bonegrave — Cling Grip required" },
        { id: "ss-crest-2", name: "Crest of Beast", location: "Hunter's March", note: "Chapel of the Beast, with Savage Beastfly" },
        { id: "ss-crest-3", name: "Crest of Reaper", location: "Greymoor", note: "Chapel of the Reaper Arena" },
        { id: "ss-crest-4", name: "Crest of Architect", location: "Underworks", note: "Chapel of the Architect — 25 Tools, 110 Rosaries required" },
        { id: "ss-crest-5", name: "Crest of Witch", location: "Shellwood", note: "Cure the Greyroot infection quest" },
        { id: "ss-crest-6", name: "Crest of Shaman", location: "Bone Bottom (Act 3)", note: "Ruined Chapel — Silk Soar required" },
      ],
    },
    {
      key: "upgrades",
      label: "Needle and Tool Upgrades",
      items: [
        { id: "ss-upgrade-1", name: "Sharpened Needle", location: "Bellhart", note: "Defeat Widow — Cling Grip required" },
        { id: "ss-upgrade-2", name: "Shining Needle", location: "Whispering Vaults", note: "Pale Oil at the west edge" },
        { id: "ss-upgrade-3", name: "Hivesteel Needle", location: "Bellhart", note: "Pale Oil after the 5 Delicacies quest" },
        { id: "ss-upgrade-4", name: "Pale Steel Needle", location: "Fleatopia", note: "Pale Oil after beating all Flea minigames" },
        { id: "ss-upgrade-5", name: "Crafting Kit 1", location: "Deep Docks", note: "Sold by Forge Daughter for 180 Rosaries" },
        { id: "ss-upgrade-6", name: "Crafting Kit 2", location: "Bellhart", note: "Craw Scarecrow quest" },
        { id: "ss-upgrade-7", name: "Crafting Kit 3", location: "Blasted Steps", note: "Sold by Grindle for 700 Rosaries" },
        { id: "ss-upgrade-8", name: "Crafting Kit 4", location: "Underworks", note: "Sold by Twelfth Architect for 450 Rosaries" },
        { id: "ss-upgrade-9", name: "Tool Pouch 1", location: "The Marrow", note: "Straight Pin aim challenge — Loddle's challenge" },
        { id: "ss-upgrade-10", name: "Tool Pouch 2", location: "Far Fields", note: "Sold in Pilgrim's Rest for 220 Rosaries" },
        { id: "ss-upgrade-11", name: "Tool Pouch 3", location: "Greymoor", note: "Nuu Hunter's Journal quest" },
        { id: "ss-upgrade-12", name: "Tool Pouch 4", location: "Putrified Ducts", note: "Find 20 Fleas, move to Fleatopia" },
      ],
    },
    {
      key: "misc",
      label: "Progress and Misc.",
      items: [
        { id: "ss-misc-1", name: "Silk Heart 1", location: "The Marrow", note: "Defeat Bell Beast" },
        { id: "ss-misc-2", name: "Silk Heart 2", location: "Whiteward", note: "Defeat The Unravelled" },
        { id: "ss-misc-3", name: "Silk Heart 3", location: "The Cradle", note: "Defeat Lace 2" },
        { id: "ss-misc-4", name: "Everbloom", location: "Bone Bottom (Act 3)", note: "Gather 3 Ancient Hearts" },
        { id: "ss-misc-5", name: "Bind Eva", location: "Weavenest Atla", note: "Max out Eva's upgrades for Sylphsong" },
      ],
    },
  ],
};

// A short, plain-text summary of checked items, grouped by category — sent with each query so the
// guide is *aware* of what the player has collected. This never touches retrieval: it's flavor
// context only, not a permission set (that's `beats`/`completed_beats`, which drives the gate).
export function collectedSummary(gameKey, collectedIds) {
  const cats = CHECKLISTS[gameKey] || [];
  const have = new Set(collectedIds || []);
  const parts = [];
  for (const cat of cats) {
    const names = cat.items.filter((it) => have.has(it.id)).map((it) => it.name);
    if (names.length) parts.push(`${cat.label}: ${names.join(", ")}`);
  }
  return parts.join("; ");
}
